### ISSUE TITLE
Speed up explore.py

### ISSUE THREAD

**Issue by dbrgn** [javaguirre/gramophone#8]
The explore part of Gramophone is really slow in a big music collection... In my collection of 55GB, it takes 13 minutes to process all metadata.

I tried to profile the process, but there doesn't seem to be much we can do about it. hsaudiotag seems to be programmed quite well, but it's Python code, no C.

Things we could do about it:
- Test whether Mutagen (also pure-Python) works faster
- Look for a faster (probably C based) alternative (this would suck because there are gcc dependencies)
- Parallelization with threading/multiprocessing
- Parallelization with gevent/greenlets

What do you think? I think the last option could work if the bottleneck is I/O. I have no idea whether it is, but it could be (when the headers are read).

**Comment by javaguirre** [comment]
I'll look into it, do some profiling to see how could we improve that with the different solutions.
