### ISSUE TITLE
Shiva

### ISSUE THREAD

**Issue by dbrgn** [javaguirre/gramophone#9]
Sorry for not having contributed anything in a while... I've been too busy with studying.

Anyways, possibly this project is suited better to host/stream music than gramophone: https://hacks.mozilla.org/2013/03/shiva-more-than-a-restful-api-to-your-music-collection/

It separates server/client into two separate RESTful projects. The client is just a sample implementation.

We could make gramophone a shiva client or dump it entirely and put our efforts into shiva directly. I think it's a pretty awesome project and has much more potential than gramophone.

**Comment by javaguirre** [comment]
I didn't have time either to contribute.

I will check out Shiva, it seems pretty interesting!
